#53 create get product/list endpoint
store-challenge/store-api pull request #22
Opened 2023-08-22 16:58 UTC by vita792

2023-08-22 17:33 UTC, dimalian requested changes

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/controller/ProductController.java
> +            @RequestParam(defaultValue = "1000000.00") Double priceTo,
you shouldn't have a default value for price. If there is no price, you need to return all items, even if the price is over 100000.

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/controller/ProductController.java
> +            products = new ArrayList<>(productFacade.findAllSortedByPriceDESC(limit, subcategoryId, priceFrom, priceTo, brand));
As I mentioned in the meeting, to sort a product you need to get 2 parameters:
**sortBy**: "price" or "alphabetical"
**orderBy**: "ASC" or "DESC"
The first parameter indicates what type to sort by.
The second parameter tells you in which direction you will sort.

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/facade/ProductFacade.java
> +    Collection<ProductPLPDto> findAllSortedByPriceASC(int limit, long subcategoryId, Double priceFrom, Double priceTo, String brand);
There shouldn't be 5 different functions for each sort type. Why not do the same as with filtering parameters?

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/facade/impl/ProductFacadeImpl.java
> +        return productService.findAllSortedByPriceASC(limit, subcategoryId, priceFrom, priceTo, brand).stream().map(ProductPLPDto::new).toList();
How many functions would you create if we had 10 parameters for sorting?

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/repository/ProductRepository.java
> +
You should feel like something went wrong when you write almost identical code 6 times.  Please, find better solution.

2023-08-22 17:33 UTC, dimalian commented on src/main/java/com/megastore/service/impl/ProductServiceImpl.java
>      }
Same here

2023-09-16 18:16 UTC, dimalian approved these changes

2023-09-16 19:56 UTC, TarasFedorenko approved these changes

2023-09-16 19:57 UTC, merged